FinalProject/Models/Recipe.cs
using System.ComponentModel.DataAnnotations;

namespace FinalProject.Models
{
  public class Recipe
  {
    public int RecipeId { get; set; }
    public string? Name { get; set; }
    public string? Description { get; set; }
    public DateOnly? Date { get; set; }
    public string? Author { get; set; }
    public string? ImagePath { get; set; }

    public string Slug =>
      Name?.Replace(" ", "-").ToLower() + "-" +
        Date?.Month + Date?.Day + Date?.Year;
  }
}

FinalProject/Controllers/AboutController.cs
// Paul Sparks

using Microsoft.AspNetCore.Mvc;
using FinalProject.Data;

namespace FinalProject.Controllers;

public class AboutController : Controller
{

    [HttpGet]
    public IActionResult Index()
    {
        return View();
    }
}

FinalProject/Controllers/AddRecipesController.cs
// Paul Sparks

using Microsoft.AspNetCore.Mvc;
using FinalProject.Data;
using FinalProject.Models;

namespace FinalProject.Controllers;

public class AddRecipesController : Controller
{
    private readonly RecipesContext _context;

    public AddRecipesController(RecipesContext context)
    {
        _context = context;
    }

    [HttpGet]
    public IActionResult Index()
    {
        var recipes = _context.Recipes.ToList();
        return View(recipes);
    }
}

FinalProject/Controllers/HomeController.cs
// Paul Sparks

using Microsoft.AspNetCore.Mvc;
using FinalProject.Data;

namespace FinalProject.Controllers;

public class HomeController : Controller
{
    private readonly RecipesContext _context;

    public HomeController(RecipesContext context)
    {
        _context = context;
    }

    [HttpGet]
    public IActionResult Recipe(int id)
    {
        var recipe = _context.Recipes.Find(id);
        return View("Recipe", recipe);
    }

    [HttpGet]
    public IActionResult Index()
    {
        var recipes = _context.Recipes.ToList();
        return View(recipes);
    }
}

FinalProject/Controllers/RecipeController.cs
using FinalProject.Data;
using FinalProject.Models;
using Microsoft.AspNetCore.Mvc;

namespace FinalProject.Controllers
{
  public class RecipeController : Controller
  {
    private RecipesContext context { get; set; }

    public RecipeController(RecipesContext ctx)
    {
      context = ctx;
    }

    [HttpGet]
    public IActionResult Add()
    {
      ViewBag.Action = "Add";
      return View("Edit", new Recipe());
    }

    [HttpGet]
    public IActionResult Edit(int id)
    {
      ViewBag.Action = "Edit";
      var recipe = context.Recipes.Find(id);
      return View(recipe);
    }

    [HttpPost]
    public IActionResult Edit(Recipe recipe)
    {
      if (ModelState.IsValid)
      {
        if (recipe.RecipeId == 0)
          context.Recipes.Add(recipe);
        else
          context.Recipes.Update(recipe);

        context.SaveChanges();
        return RedirectToAction("Index", "Home");
      }
      else
      {
        ViewBag.Action = (recipe.RecipeId == 0) ? "Add" : "Edit";
        return View(recipe);
      }
    }

    [HttpGet]
    public IActionResult Delete(int id)
    {
      var recipe = context.Recipes.Find(id);
      return View(recipe);
    }

    [HttpPost]
    public IActionResult Delete(Recipe recipe)
    {
      context.Recipes.Remove(recipe);
      context.SaveChanges();
      return RedirectToAction("Index", "Home");
    }
  }
}

FinalProject/Views/About/Index.cshtml
<div style="margin-left: auto; margin-right: auto; width: 60%;">
    <p>
        Welcome to my culinary corner! My name is Paul Sparks, and I’m a passionate home chef who believes that great
        food brings people together. Growing up, my kitchen was the heart of the home, and some of my fondest memories
        revolve around the smell of freshly baked bread, the sizzle of a skillet, and the joy of sharing a meal with
        loved ones. Over the years, I’ve honed my craft by experimenting with flavors, techniques, and ingredients from
        around the world, creating recipes that are as accessible as they are delicious. Whether you’re a seasoned cook
        or just starting your journey, my goal is to inspire you to dive into the kitchen and discover the magic of
        homemade meals.
        Here on my recipe website, you’ll find a collection of dishes that reflect my philosophy: simple, flavorful, and
        made with love. From comforting classics to adventurous twists, every recipe is designed to empower you to
        create something extraordinary in your own kitchen.
    </p>
</div>

FinalProject/Views/AddRecipes/Index.cshtml
@model List<Recipe>
@{
    ViewData["Title"] = "Add Recipes";
}

<a asp-controller="Recipe" asp-action="Add">Add New Recipe</a>
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Name</th>
            <th>Date</th>
            <th>Author</th>
            <th>Description</th>
            <th>Image Path</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var recipe in Model)
        {
            <tr>
                <td>@recipe.Name</td>
                <td>@recipe.Date</td>
                <td>@recipe.Author</td>
                <td>@recipe.Description</td>
                <td>@recipe.ImagePath</td>
                <td>
                    <a asp-controller="Recipe" asp-action="Edit" asp-route-id="@recipe.RecipeId"
                        asp-route-slug="@recipe.Slug">
                        Edit
                    </a>
                    <a asp-controller="Recipe" asp-action="Delete" asp-route-id="@recipe.RecipeId"
                        asp-route-slug="@recipe.Slug">
                        Delete
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>

FinalProject/Views/Home/Index.cshtml
@model List<Recipe>
@{
    ViewData["Title"] = "Home";
}

<h1 style="margin-bottom: 30px;">Recipes</h1>

<div class=" container">
    <div class="row">
        @for (int i = 0; i < Model.Count; i++)
{
            <div class="col-12 col-lg-6 col-xxl-4">
                <div class="card" style="width: 24rem; margin-bottom: 30px;">
            @if (Model[i].ImagePath != null)
            {
                        <img src="@Model[i].ImagePath" class="card-img-top img-fluid">
            }
                    <div class="card-body">
                        <h5 class="card-title">@Model[i].Name</h5>
                        <p style="color: grey;" class="card-text text-truncate">@Model[i].Description</p>
                        <a asp-controller="Home" asp-action="Recipe" asp-route-id="@Model[i].RecipeId"
                            asp-route-slug="@Model[i].Slug" class="btn btn-primary">See Recipe</a>
                    </div>
                </div>
            </div>
}
    </div>
    </div>

FinalProject/Views/Home/Recipe.cshtml
@model Recipe
@{
    ViewData["Title"] = Model.Name;
}
<div class="container">
    <div class="row">
        <h1>@Model.Name</h1>
        <h2 style="font-size: large">@Model.Author, @Model.Date</h2>
    </div>
    <div class="row">
        <div class="col-6 col-lg-4">
            <img class="img-fluid" src="@Model.ImagePath">
        </div>
        <div class="col">
            <p>@Model.Description</p>
            <a asp-controller="Home" asp-action="Index" class="btn btn-primary">
                Back
            </a>
        </div>
    </div>
</div>

FinalProject/Views/Movie/Delete.cshtml
@model Movie
@{
  ViewBag.Title = "Delete Movie";
}

<h2>Confirm Deletion</h2>
<h3>@Model.Name (@Model.Year)</h3>

<form asp-action="Delete" method="post">
  <input type="hidden" asp-for="MovieId" />

  <button type="submit" class="btn btn-primary">Delete</button>
  <a asp-asp-controller="Home" asp-action="Index" class="btn btn-primary">
    Cancel
  </a>
</form>

FinalProject/Views/Recipe/Delete.cshtml
@model Recipe
@{
  ViewBag.Title = "Delete Recipe";
}

<h2>Confirm Deletion</h2>
<h3>@Model.Name (@Model.Date)</h3>

<form asp-action="Delete" method="post">
  <input type="hidden" asp-for="RecipeId" />

  <button type="submit" class="btn btn-primary">Delete</button>
  <a asp-asp-controller="Home" asp-action="Index" class="btn btn-primary">
    Cancel
  </a>
</form>

FinalProject/Views/Recipe/Edit.cshtml
@model Recipe
@{
  string title = ViewBag.Action + " Recipe";
  ViewBag.Title = title;
}

<h2>@ViewBag.Title</h2>

<form asp-action="Edit" method="post">
  <div asp-validation-summary="All" class="text-danger"></div>

  <div class="form-group">
    <label asp-for="Name">Name</label>
    <input asp-for="Name" class="form-control">
  </div>

  <div class="form-group">
    <label asp-for="Date">Date</label>
    <input asp-for="Date" class="form-control">
  </div>

  <div class="form-group">
    <label asp-for="Author">Author</label>
    <input asp-for="Author" class="form-control">
  </div>

  <div class="form-group">
    <label asp-for="Description">Description</label>
    <textarea asp-for="Description" class="form-control"></textarea>
  </div>

  <div class="form-group" style="margin-bottom: 20px;">
    <label asp-for="ImagePath">Image Path</label>
    <input asp-for="ImagePath" class="form-control">
  </div>

  <input type="hidden" asp-for="RecipeId" />

  <button type="submit" class="btn btn-primary">@ViewBag.Action</button>
  <a asp-controller="AddRecipes" asp-action="Index" class="btn btn-primary">
    Cancel
  </a>
</form>

FinalProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FinalProject.styles.css" asp-append-version="true" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Paul's Cookbook</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AddRecipes" asp-action="Index">Add
                                Recipes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="About"
                                asp-action="Index">About</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - FinalProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>